"""Out-of-sample check of the "faster than the sun" flag -> docs/flag-check.md (no AWS needed).

    python backend/scripts/flag_check.py

We have no ground truth for pumping, so this tests what the flag can be held to: at each past date, ponds
flagged then (from data up to that date only) should keep losing water faster than unflagged ponds over the
NEXT 30 days, which the flag never saw, and dry sooner. If the flag were noise, both groups would look alike.
It shows the flag finds ponds that really lose water fast; it cannot show why (pumping, a shallow bed, seepage).
"""
import json
import statistics
import sys
from datetime import timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "backend"))

from logic.backtest import _d, actual_dry_window  # noqa: E402
from logic.snapshot import build_snapshot  # noqa: E402

REGIONS = [("latur-district-2024", "Latur district 2024 (435 ponds)"), ("latur-2024", "Latur box 2024"),
           ("latur-2023", "Latur box 2023 (held out)")]
AHEAD_DAYS, DRY_WITHIN_DAYS, NEAREST_DAYS, MIN_AREA_HA = 30, 60, 6, 2.0  # MIN_AREA_HA: the flag's own size rule


def area_near(history: list[dict], day, tol: int = NEAREST_DAYS) -> float | None:
    near = [(abs((_d(h["date"]) - day).days), h["areaHa"]) for h in history if h["valid"]]
    near = [x for x in near if x[0] <= tol]
    return min(near)[1] if near else None


def check(meas: dict) -> dict:
    history = {p["id"]: p["history"] for p in meas["ponds"]}
    truth = {p["id"]: actual_dry_window(p["history"]) for p in meas["ponds"]}
    dates = [s["date"] for s in meas["scenes"]]
    first, last = _d(dates[0]) + timedelta(days=20), _d(dates[-1])
    loss = {True: [], False: []}
    dried = {True: [0, 0], False: [0, 0]}
    for t_str in dates:
        t = _d(t_str)
        if t < first or t + timedelta(days=AHEAD_DAYS) > last:
            continue
        for p in build_snapshot(meas, t)["ponds"]:
            if p["status"] in ("dry", "unknown") or p.get("shrinkVsNeighbours") is None or p["maxAreaHa"] < MIN_AREA_HA:
                continue  # only ponds the flag could have judged
            a0, a1 = area_near(history[p["id"]], t), area_near(history[p["id"]], t + timedelta(days=AHEAD_DAYS))
            if a0 is None or a1 is None:
                continue
            flagged = p.get("flag") == "faster-than-sun"
            loss[flagged].append((a0 - a1) / p["maxAreaHa"])
            win = truth[p["id"]]
            dried[flagged][0] += 1
            dried[flagged][1] += bool(win and (win[0] - t).days <= DRY_WITHIN_DAYS)
    return {f: {"n": len(loss[f]), "loss": statistics.median(loss[f]) if loss[f] else None,
                "dried": dried[f][1], "of": dried[f][0]} for f in (True, False)}


def pct(x: float | None) -> str:
    return "–" if x is None else f"{x * 100:.1f}%"


def main() -> None:
    rows = []
    for region, label in REGIONS:
        r = check(json.loads((ROOT / "data" / region / "measurements.json").read_text(encoding="utf-8")))
        f, n = r[True], r[False]
        rows.append(f"| {label} | **{pct(f['loss'])}** (n={f['n']}) | {pct(n['loss'])} (n={n['n']}) | "
                    f"**{f['dried']}/{f['of']}** ({pct(f['dried'] / f['of'] if f['of'] else None)}) | "
                    f"{n['dried']}/{n['of']} ({pct(n['dried'] / n['of'] if n['of'] else None)}) |")
        print(rows[-1])
    doc = f"""# Does the "faster than the sun" flag mean anything?

Generated by `python backend/scripts/flag_check.py` from the committed measurements.

We have **no ground truth for pumping**: nobody records which ponds are pumped. So we test what the flag can
honestly be held to. At every past date, each pond the flag could judge (not dry, visible, at least
{MIN_AREA_HA:g} ha) is either flagged or not, using only data up to that date. Then we look at the **next
{AHEAD_DAYS} days**, which the flag never saw: how much of its full area did it lose, and did it dry within
{DRY_WITHIN_DAYS} days? If the flag were noise, flagged and unflagged ponds would look alike.

| Season | Water lost in the next {AHEAD_DAYS} days, flagged (median, share of full area) | Unflagged | Dried within {DRY_WITHIN_DAYS} days, flagged | Unflagged |
|---|---|---|---|---|
{chr(10).join(rows)}

**What this shows:** a flagged pond really does keep losing water much faster than its neighbours under the
same sun, and dries far sooner, in every season including the one we never tuned on. The flag is not noise.

**What it does not show:** *why*. Pumping is one cause; a shallow bed, seepage or a legal irrigation offtake
are others. That is why Talaab says a flag "suggests pumping; worth an inspection" and never that a pond
**is** being pumped. The inspection list is a way to send scarce inspectors to the ponds most worth a visit.
"""
    (ROOT / "docs" / "flag-check.md").write_text(doc, encoding="utf-8")
    print("wrote docs/flag-check.md")


if __name__ == "__main__":
    main()
